AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: MyApi
      StageName: prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: My API
          version: '1.0'
        paths:
          /hello:
            get:
              x-amazon-apigateway-integration:
                type: MOCK
                httpMethod: POST
                requestTemplates:
                  application/json: "{ \"statusCode\": 200 }"
              responses:
                '200':
                  description: 200 response
          /goodbye:
            post:
              x-amazon-apigateway-integration:
                type: MOCK
                httpMethod: POST
                requestTemplates:
                  application/json: "{ \"statusCode\": 200 }"
              responses:
                '200':
                  description: 200 response